name: Deploy to Airflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync DAGs folder to Airflow server
        run: |
          rsync -avz ./dags/ $AIRFLOW_HOME/dags/
        env:
          AIRFLOW_HOME: /home/airflow/airflow